steps:
- id: go_version
  name: "gcr.io/cloud-builders/go"
  args: ["version"]
  env: ["GOPATH=."]

- id: "Compilando"
  name: 'gcr.io/cloud-builders/go'
  args: ['build', 'soma.go']
  env: ["GOPATH=."]

- id: "rodando testes unitarios"
  name: 'gcr.io/cloud-builders/go'
  args: ['test']
  env: ["GOPATH=."]

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'version=1.0.0'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio-ci:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio-ci:1.0.0'
  - '.'
images:
  - 'gcr.io/$PROJECT_ID/desafio-ci:1.0.0'
# - 'gcr.io/$PROJECT_ID/desafio-ci:latest'
# tags: ['cloud-builders-community']
